---
title: "2.Aplicaciones del RNA-Seq"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
date: "`r Sys.Date()`"
---

# Principales aplicaciones

--

- Expresión cuantitativa de loci

--

- Detección de variantes 

--

- Redes de co-expresión

--

- Secuenciación de célula única

--

- Fusión de genes

--


- **Análisis de expresión diferencial**

---

# Expresión cuantitativa de loci (EQTL)

--

- Relacionado con el estudio de rasgos

--

- Relaciona cambios en la expresión de genes a SNPs conocidos

--

- Determinar el efecto en el fenotipo -> mecanismos en *cis-* o en *trans-*

--

- WGS y (variantes) y epigenómica (silencialmiento) para complementar los datos

--

- Útil para la investigación de enfermedades o agronomía

---

# Detección de variantes

--

- Alternativa al estudio clásico de variantes (WGS o WES)

--

- Presenta limitaciones relacionadas con la cobertura y la profundidad (cobertura mayor a 10X)

--

- Se han reportado resultados en donde se identificaron > 8000 SNPs en músculo de *Longissimus thoraci*

--

- Enfocado en la porción transcrita del genoma

---

# Redes de co-expresión

--

- Asociación entre dos o más genes por medio de expresión coordinada

--

- Genes co-expresados -> funciones relacionadas, mecanismos de regulación similar 

--

- RNA-seq permite obtener redes de co-expresión más completas que los microarreglos

--

- Requiere amplio número de muestras (al menos 20) 

---

# Fusión de genes

--

- Asociado a eventos de rearreglos genómicos como amplificaciones, deleciones y translocaciones

--

- Región 5' gen A -> Region 3' gen B

--

- RNA-seq permite conocer fusiones génicas en el desarrollo de enfermedades como cáncer

--

- Permite conocer las diferencias en la expresión de genes fusionados entre dos condiciones


---

# Análisis de expresión diferencial

--  

- Aplicación más común del RNA-seq

--

- Permite identificar y cuantificar la expresión de transcritos entre dos grupos distintos

--

- Etapas del desarrollo, tejidos distintos, efecto de estímulos o tratamientos

--

- Requiere del uso de modelos estadísticos que evaluen la expresión diferencial 

--

- Normalización de los datos (tamaño de la librería, longitud de los genes, composición de la librería...)


